"""
エクスポートモジュール
日次サマリー・月次サマリーを Markdown / PDF 形式でエクスポートします。
"""

import io
import logging
from datetime import date, timedelta
from typing import Any, Optional

from .database import (
    get_daily_summary,
    get_timeline,
    get_hourly_breakdown,
    get_calendar_events,
    get_monthly_report,
    get_weekly_report,
)

logger = logging.getLogger(__name__)


# ─── ユーティリティ ───────────────────────────────────────────

def _fmt_duration(seconds: float) -> str:
    """秒数を 'Xh Ym' 形式に変換する"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    if h > 0:
        return f"{h}h {m}m"
    return f"{m}m"


def _fmt_duration_hm(seconds: float) -> str:
    """秒数を 'X時間Y分' 形式に変換する"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    if h > 0:
        return f"{h}時間{m}分"
    return f"{m}分"


def _weekday_ja(d: date) -> str:
    """日本語の曜日を返す"""
    weekdays = ["月", "火", "水", "木", "金", "土", "日"]
    return weekdays[d.weekday()]


# ─── 日次サマリー Markdown ────────────────────────────────────

def export_daily_markdown(target_date: str) -> str:
    """日次サマリーを Markdown 文字列としてエクスポートする"""
    summary = get_daily_summary(target_date)
    hourly = get_hourly_breakdown(target_date)
    events = get_calendar_events(target_date)

    total_seconds = sum(r.get("total_seconds", 0) for r in summary)
    d = date.fromisoformat(target_date)

    lines = []
    lines.append(f"# 📊 日次サマリー — {target_date} ({_weekday_ja(d)})")
    lines.append("")
    lines.append(f"**合計作業時間:** {_fmt_duration_hm(total_seconds)}")
    lines.append("")

    # プロジェクト別集計
    projects: dict[str, float] = {}
    phases: dict[str, float] = {}
    apps: dict[str, float] = {}
    for r in summary:
        pj = r.get("project") or "(未分類)"
        wp = r.get("work_phase") or "(未分類)"
        app = r.get("app_name") or ""
        sec = r.get("total_seconds", 0)
        projects[pj] = projects.get(pj, 0) + sec
        phases[wp] = phases.get(wp, 0) + sec
        apps[app] = apps.get(app, 0) + sec

    if projects:
        lines.append("## 📁 プロジェクト別")
        lines.append("")
        lines.append("| プロジェクト | 時間 | 割合 |")
        lines.append("|---|---|---|")
        for pj, sec in sorted(projects.items(), key=lambda x: -x[1]):
            pct = (sec / total_seconds * 100) if total_seconds > 0 else 0
            bar = "█" * int(pct / 5)
            lines.append(f"| {pj} | {_fmt_duration(sec)} | {bar} {pct:.0f}% |")
        lines.append("")

    if phases:
        lines.append("## 🏷 作業工程別")
        lines.append("")
        lines.append("| 作業工程 | 時間 | 割合 |")
        lines.append("|---|---|---|")
        for wp, sec in sorted(phases.items(), key=lambda x: -x[1]):
            pct = (sec / total_seconds * 100) if total_seconds > 0 else 0
            bar = "█" * int(pct / 5)
            lines.append(f"| {wp} | {_fmt_duration(sec)} | {bar} {pct:.0f}% |")
        lines.append("")

    if apps:
        lines.append("## 💻 アプリ別")
        lines.append("")
        lines.append("| アプリ | 時間 | 割合 |")
        lines.append("|---|---|---|")
        for app, sec in sorted(apps.items(), key=lambda x: -x[1])[:10]:
            pct = (sec / total_seconds * 100) if total_seconds > 0 else 0
            lines.append(f"| {app} | {_fmt_duration(sec)} | {pct:.0f}% |")
        lines.append("")

    # 時間帯別
    if hourly:
        lines.append("## ⏰ 時間帯別")
        lines.append("")
        hour_totals: dict[str, float] = {}
        for r in hourly:
            h = r.get("hour", "00")
            sec = r.get("total_seconds", 0)
            hour_totals[h] = hour_totals.get(h, 0) + sec

        lines.append("| 時間帯 | 作業時間 | グラフ |")
        lines.append("|---|---|---|")
        for h in [f"{i:02d}" for i in range(24)]:
            sec = hour_totals.get(h, 0)
            if sec > 0:
                bar = "▓" * int(sec / 300)  # 5min per block
                lines.append(f"| {h}:00 | {_fmt_duration(sec)} | {bar} |")
        lines.append("")

    # カレンダーイベント
    if events:
        lines.append("## 📅 カレンダーイベント")
        lines.append("")
        for ev in events:
            start = ev.get("start_time", "")[-8:-3] if ev.get("start_time") else ""
            end = ev.get("end_time", "")[-8:-3] if ev.get("end_time") else ""
            title = ev.get("title", "")
            lines.append(f"- {start} - {end}: {title}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by TimeReaper*")

    return "\n".join(lines)


# ─── 月次サマリー Markdown ────────────────────────────────────

def export_monthly_markdown(year: int, month: int) -> str:
    """月次サマリーを Markdown 文字列としてエクスポートする"""
    report = get_monthly_report(year, month)
    totals = report["totals"]
    total_seconds = totals["total_seconds"]

    lines = []
    lines.append(f"# 📊 月次サマリー — {year}年{month}月")
    lines.append("")
    lines.append(f"**期間:** {report['month_start']} 〜 {report['month_end']}")
    lines.append(f"**合計作業時間:** {_fmt_duration_hm(total_seconds)}")

    # 稼働日数
    active_days = len([d for d in report["days"] if d["total_seconds"] > 0])
    if active_days > 0:
        avg_sec = total_seconds / active_days
        lines.append(f"**稼働日数:** {active_days}日（日平均: {_fmt_duration_hm(avg_sec)}）")
    lines.append("")

    # 週別サマリー
    if report.get("weekly_totals"):
        lines.append("## 📅 週別作業時間")
        lines.append("")
        lines.append("| 週 | 作業時間 | グラフ |")
        lines.append("|---|---|---|")
        max_week_sec = max(w["total_seconds"] for w in report["weekly_totals"]) if report["weekly_totals"] else 1
        for w in report["weekly_totals"]:
            bar_len = int(w["total_seconds"] / max_week_sec * 20) if max_week_sec > 0 else 0
            bar = "█" * bar_len
            lines.append(f"| {w['week_start']}〜 | {_fmt_duration(w['total_seconds'])} | {bar} |")
        lines.append("")

    # プロジェクト別
    by_project = totals.get("by_project", {})
    if by_project:
        lines.append("## 📁 プロジェクト別")
        lines.append("")
        lines.append("| プロジェクト | 時間 | 割合 |")
        lines.append("|---|---|---|")
        for pj, sec in sorted(by_project.items(), key=lambda x: -x[1]):
            pct = (sec / total_seconds * 100) if total_seconds > 0 else 0
            bar = "█" * int(pct / 5)
            lines.append(f"| {pj} | {_fmt_duration(sec)} | {bar} {pct:.0f}% |")
        lines.append("")

    # 作業工程別
    by_phase = totals.get("by_phase", {})
    if by_phase:
        lines.append("## 🏷 作業工程別")
        lines.append("")
        lines.append("| 作業工程 | 時間 | 割合 |")
        lines.append("|---|---|---|")
        for wp, sec in sorted(by_phase.items(), key=lambda x: -x[1]):
            pct = (sec / total_seconds * 100) if total_seconds > 0 else 0
            bar = "█" * int(pct / 5)
            lines.append(f"| {wp} | {_fmt_duration(sec)} | {bar} {pct:.0f}% |")
        lines.append("")

    # アプリ別
    by_app = totals.get("by_app", {})
    if by_app:
        lines.append("## 💻 アプリ別 (Top 15)")
        lines.append("")
        lines.append("| アプリ | 時間 | 割合 |")
        lines.append("|---|---|---|")
        for app, sec in sorted(by_app.items(), key=lambda x: -x[1])[:15]:
            pct = (sec / total_seconds * 100) if total_seconds > 0 else 0
            lines.append(f"| {app} | {_fmt_duration(sec)} | {pct:.0f}% |")
        lines.append("")

    # 日別推移
    lines.append("## 📈 日別推移")
    lines.append("")
    lines.append("| 日付 | 曜日 | 作業時間 | グラフ |")
    lines.append("|---|---|---|---|")
    max_day_sec = max((d["total_seconds"] for d in report["days"]), default=1) or 1
    for d_info in report["days"]:
        d_dt = date.fromisoformat(d_info["date"])
        sec = d_info["total_seconds"]
        if sec > 0:
            bar_len = int(sec / max_day_sec * 20)
            bar = "▓" * bar_len
            lines.append(f"| {d_info['date']} | {_weekday_ja(d_dt)} | {_fmt_duration(sec)} | {bar} |")
    lines.append("")

    lines.append("---")
    lines.append(f"*Generated by TimeReaper*")

    return "\n".join(lines)


# ─── 日次サマリー PDF ─────────────────────────────────────────

def export_daily_pdf(target_date: str) -> bytes:
    """日次サマリーを視覚的な PDF としてエクスポートする"""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.graphics.shapes import Drawing, Rect, String, Line
    from reportlab.graphics.charts.piecharts import Pie
    from reportlab.graphics.charts.barcharts import HorizontalBarChart
    from reportlab.platypus.flowables import KeepTogether

    summary = get_daily_summary(target_date)
    hourly = get_hourly_breakdown(target_date)
    events = get_calendar_events(target_date)

    total_seconds = sum(r.get("total_seconds", 0) for r in summary)
    d = date.fromisoformat(target_date)

    # データ集計
    projects: dict[str, float] = {}
    phases: dict[str, float] = {}
    apps: dict[str, float] = {}
    for r in summary:
        pj = r.get("project") or "(未分類)"
        wp = r.get("work_phase") or "(未分類)"
        app = r.get("app_name") or ""
        sec = r.get("total_seconds", 0)
        projects[pj] = projects.get(pj, 0) + sec
        phases[wp] = phases.get(wp, 0) + sec
        apps[app] = apps.get(app, 0) + sec

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=15 * mm, bottomMargin=15 * mm,
    )

    # --- スタイル定義 ---
    styles = getSampleStyleSheet()
    _register_japanese_font()

    style_title = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontName="HeiseiKakuGo-W5", fontSize=20, leading=26,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=4,
    )
    style_subtitle = ParagraphStyle(
        "CustomSubtitle", parent=styles["Normal"],
        fontName="HeiseiKakuGo-W5", fontSize=11,
        textColor=colors.HexColor("#666666"),
        spaceAfter=12,
    )
    style_section = ParagraphStyle(
        "SectionHeader", parent=styles["Heading2"],
        fontName="HeiseiKakuGo-W5", fontSize=14, leading=20,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=16, spaceAfter=8,
        borderWidth=0,
    )
    style_body = ParagraphStyle(
        "CustomBody", parent=styles["Normal"],
        fontName="HeiseiKakuGo-W5", fontSize=10, leading=14,
        textColor=colors.HexColor("#333333"),
    )
    style_small = ParagraphStyle(
        "SmallText", parent=styles["Normal"],
        fontName="HeiseiKakuGo-W5", fontSize=8, leading=10,
        textColor=colors.HexColor("#888888"),
    )

    elements = []

    # --- ヘッダー ---
    elements.append(Paragraph(f"日次サマリー", style_title))
    elements.append(Paragraph(
        f"{target_date} ({_weekday_ja(d)})　|　合計作業時間: {_fmt_duration_hm(total_seconds)}",
        style_subtitle,
    ))
    elements.append(HRFlowable(
        width="100%", thickness=2,
        color=colors.HexColor("#4a90d9"), spaceAfter=12,
    ))

    # --- サマリーカード（テーブルで疑似カード表現）---
    card_data = [
        [
            _make_stat_card("合計作業時間", _fmt_duration_hm(total_seconds), "#4a90d9"),
            _make_stat_card("プロジェクト数", str(len(projects)), "#3fb950"),
            _make_stat_card("使用アプリ数", str(len(apps)), "#bc8cff"),
        ]
    ]
    card_table = Table(card_data, colWidths=[55 * mm, 55 * mm, 55 * mm])
    card_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(card_table)
    elements.append(Spacer(1, 10))

    # --- プロジェクト別 横棒グラフ ---
    if projects:
        elements.append(Paragraph("プロジェクト別 作業時間", style_section))
        chart_and_table = _build_horizontal_bar_section(projects, total_seconds)
        elements.extend(chart_and_table)

    # --- 作業工程別 円グラフ ---
    if phases:
        elements.append(Paragraph("作業工程別 内訳", style_section))
        pie_and_legend = _build_pie_section(phases, total_seconds)
        elements.extend(pie_and_legend)

    # --- アプリ別テーブル ---
    if apps:
        elements.append(Paragraph("アプリ別 作業時間", style_section))
        app_table = _build_detail_table(
            headers=["アプリ", "時間", "割合"],
            data=[
                (app, _fmt_duration(sec), f"{sec / total_seconds * 100:.1f}%" if total_seconds > 0 else "0%")
                for app, sec in sorted(apps.items(), key=lambda x: -x[1])[:10]
            ],
        )
        elements.append(app_table)
        elements.append(Spacer(1, 8))

    # --- 時間帯別アクティビティバー ---
    if hourly:
        elements.append(Paragraph("時間帯別 アクティビティ", style_section))
        hour_chart = _build_hourly_chart(hourly)
        elements.append(hour_chart)
        elements.append(Spacer(1, 8))

    # --- カレンダーイベント ---
    if events:
        elements.append(Paragraph("カレンダーイベント", style_section))
        ev_data = []
        for ev in events:
            start = ev.get("start_time", "")[-8:-3] if ev.get("start_time") else ""
            end = ev.get("end_time", "")[-8:-3] if ev.get("end_time") else ""
            title = ev.get("title", "")
            ev_data.append((f"{start} - {end}", title))
        ev_table = _build_detail_table(
            headers=["時間", "イベント"],
            data=ev_data,
            col_widths=[35 * mm, 130 * mm],
        )
        elements.append(ev_table)

    # --- フッター ---
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(
        width="100%", thickness=1,
        color=colors.HexColor("#cccccc"), spaceAfter=6,
    ))
    elements.append(Paragraph("Generated by TimeReaper", style_small))

    doc.build(elements)
    return buf.getvalue()


# ─── 月次サマリー PDF ─────────────────────────────────────────

def export_monthly_pdf(year: int, month: int) -> bytes:
    """月次サマリーを視覚的な PDF としてエクスポートする"""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER
    from reportlab.graphics.shapes import Drawing, Rect, String

    report = get_monthly_report(year, month)
    totals = report["totals"]
    total_seconds = totals["total_seconds"]

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=15 * mm, bottomMargin=15 * mm,
    )

    styles = getSampleStyleSheet()
    _register_japanese_font()

    style_title = ParagraphStyle(
        "CustomTitle2", parent=styles["Title"],
        fontName="HeiseiKakuGo-W5", fontSize=20, leading=26,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=4,
    )
    style_subtitle = ParagraphStyle(
        "CustomSubtitle2", parent=styles["Normal"],
        fontName="HeiseiKakuGo-W5", fontSize=11,
        textColor=colors.HexColor("#666666"),
        spaceAfter=12,
    )
    style_section = ParagraphStyle(
        "SectionHeader2", parent=styles["Heading2"],
        fontName="HeiseiKakuGo-W5", fontSize=14, leading=20,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=16, spaceAfter=8,
        borderWidth=0,
    )
    style_small = ParagraphStyle(
        "SmallText2", parent=styles["Normal"],
        fontName="HeiseiKakuGo-W5", fontSize=8, leading=10,
        textColor=colors.HexColor("#888888"),
    )

    elements = []

    # --- ヘッダー ---
    active_days = len([d for d in report["days"] if d["total_seconds"] > 0])
    elements.append(Paragraph(f"月次サマリー", style_title))
    elements.append(Paragraph(
        f"{year}年{month}月　|　合計: {_fmt_duration_hm(total_seconds)}　|　稼働日: {active_days}日",
        style_subtitle,
    ))
    elements.append(HRFlowable(
        width="100%", thickness=2,
        color=colors.HexColor("#4a90d9"), spaceAfter=12,
    ))

    # --- サマリーカード ---
    avg_sec = total_seconds / active_days if active_days > 0 else 0
    by_project = totals.get("by_project", {})
    by_app = totals.get("by_app", {})
    card_data = [
        [
            _make_stat_card("合計作業時間", _fmt_duration_hm(total_seconds), "#4a90d9"),
            _make_stat_card("日平均", _fmt_duration_hm(avg_sec), "#3fb950"),
            _make_stat_card("プロジェクト数", str(len(by_project)), "#bc8cff"),
        ]
    ]
    card_table = Table(card_data, colWidths=[55 * mm, 55 * mm, 55 * mm])
    card_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(card_table)
    elements.append(Spacer(1, 10))

    # --- 日別推移グラフ ---
    elements.append(Paragraph("日別 作業時間", style_section))
    daily_chart = _build_daily_trend_chart(report["days"])
    elements.append(daily_chart)
    elements.append(Spacer(1, 8))

    # --- プロジェクト別 ---
    if by_project:
        elements.append(Paragraph("プロジェクト別 作業時間", style_section))
        chart_and_table = _build_horizontal_bar_section(by_project, total_seconds)
        elements.extend(chart_and_table)

    # --- 作業工程別 ---
    by_phase = totals.get("by_phase", {})
    if by_phase:
        elements.append(Paragraph("作業工程別 内訳", style_section))
        pie_items = _build_pie_section(by_phase, total_seconds)
        elements.extend(pie_items)

    # --- アプリ別 ---
    if by_app:
        elements.append(Paragraph("アプリ別 作業時間 (Top 15)", style_section))
        app_table = _build_detail_table(
            headers=["アプリ", "時間", "割合"],
            data=[
                (app, _fmt_duration(sec), f"{sec / total_seconds * 100:.1f}%" if total_seconds > 0 else "0%")
                for app, sec in sorted(by_app.items(), key=lambda x: -x[1])[:15]
            ],
        )
        elements.append(app_table)

    # --- フッター ---
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(
        width="100%", thickness=1,
        color=colors.HexColor("#cccccc"), spaceAfter=6,
    ))
    elements.append(Paragraph("Generated by TimeReaper", style_small))

    doc.build(elements)
    return buf.getvalue()


# ─── PDF 内部ヘルパー ─────────────────────────────────────────

_font_registered = False


def _register_japanese_font():
    """日本語フォントを登録する（reportlab 内蔵の CID フォントを使用）"""
    global _font_registered
    if _font_registered:
        return

    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.cidfonts import UnicodeCIDFont

    # reportlab 内蔵の CID フォント（日本語ゴシック体）
    # macOS のヒラギノは PostScript アウトラインのため TTFont では読めない
    pdfmetrics.registerFont(UnicodeCIDFont("HeiseiKakuGo-W5"))
    pdfmetrics.registerFont(UnicodeCIDFont("HeiseiMin-W3"))

    _font_registered = True


def _make_stat_card(label: str, value: str, color_hex: str):
    """統計カード風のテーブルセルを作成する"""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.platypus import Table, TableStyle, Paragraph
    from reportlab.lib.styles import ParagraphStyle

    p_label = Paragraph(
        label,
        ParagraphStyle("cl", fontName="HeiseiKakuGo-W5", fontSize=9,
                        textColor=colors.HexColor("#666666"), leading=12),
    )
    p_value = Paragraph(
        f'<font color="{color_hex}"><b>{value}</b></font>',
        ParagraphStyle("cv", fontName="HeiseiKakuGo-W5", fontSize=18,
                        textColor=colors.HexColor(color_hex), leading=24),
    )

    t = Table([[p_label], [p_value]], colWidths=[50 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8f9fa")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#e0e0e0")),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))
    return t


def _build_detail_table(
    headers: list[str],
    data: list[tuple],
    col_widths: Optional[list] = None,
):
    """スタイル付きの詳細テーブルを生成する"""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.platypus import Table, TableStyle, Paragraph
    from reportlab.lib.styles import ParagraphStyle

    style_header = ParagraphStyle(
        "th", fontName="HeiseiKakuGo-W5", fontSize=9,
        textColor=colors.white, leading=12,
    )
    style_cell = ParagraphStyle(
        "td", fontName="HeiseiKakuGo-W5", fontSize=9,
        textColor=colors.HexColor("#333333"), leading=12,
    )

    table_data = [[Paragraph(h, style_header) for h in headers]]
    for row in data:
        table_data.append([Paragraph(str(c), style_cell) for c in row])

    if col_widths is None:
        n = len(headers)
        col_widths = [165 / n * mm] * n

    t = Table(table_data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4a90d9")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "HeiseiKakuGo-W5"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#ffffff")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#ffffff"), colors.HexColor("#f5f7fa")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return t


def _build_horizontal_bar_section(
    data_dict: dict[str, float],
    total_seconds: float,
) -> list:
    """横棒グラフ + 凡例テーブルを返す"""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.graphics.shapes import Drawing, Rect, String
    from reportlab.platypus import Spacer

    palette = [
        "#4a90d9", "#3fb950", "#bc8cff", "#f0883e",
        "#f85149", "#d29922", "#39d2c0", "#ff6b9d",
        "#7eb0d5", "#b2df8a",
    ]

    sorted_items = sorted(data_dict.items(), key=lambda x: -x[1])[:8]
    max_val = max(v for _, v in sorted_items) if sorted_items else 1

    drawing = Drawing(170 * mm, len(sorted_items) * 22 + 10)
    bar_width = 100 * mm
    y_start = len(sorted_items) * 22

    for i, (name, sec) in enumerate(sorted_items):
        y = y_start - (i + 1) * 22 + 5
        color = colors.HexColor(palette[i % len(palette)])

        # ラベル
        drawing.add(String(0, y + 4, name, fontName="HeiseiKakuGo-W5", fontSize=9,
                           fillColor=colors.HexColor("#333333")))

        # バー
        w = (sec / max_val) * bar_width if max_val > 0 else 0
        drawing.add(Rect(55 * mm, y, w, 14, fillColor=color, strokeColor=None,
                         rx=3, ry=3))

        # 値ラベル
        pct = (sec / total_seconds * 100) if total_seconds > 0 else 0
        drawing.add(String(
            55 * mm + w + 3, y + 3,
            f"{_fmt_duration(sec)} ({pct:.0f}%)",
            fontName="HeiseiKakuGo-W5", fontSize=8,
            fillColor=colors.HexColor("#666666"),
        ))

    return [drawing, Spacer(1, 8)]


def _build_pie_section(
    data_dict: dict[str, float],
    total_seconds: float,
) -> list:
    """円グラフ + 凡例を返す"""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.graphics.shapes import Drawing, Rect, String, Circle
    from reportlab.platypus import Spacer

    palette = [
        "#4a90d9", "#3fb950", "#bc8cff", "#f0883e",
        "#f85149", "#d29922", "#39d2c0", "#ff6b9d",
        "#7eb0d5", "#b2df8a",
    ]

    sorted_items = sorted(data_dict.items(), key=lambda x: -x[1])[:8]

    # 円グラフをDrawingで手動描画（シンプルな割合バー表現）
    drawing = Drawing(170 * mm, max(len(sorted_items) * 18 + 10, 40))

    # 割合バー（ステップバー風）
    total_w = 160 * mm
    x_offset = 5 * mm
    bar_h = 18

    # 上部: カラーバー
    x = x_offset
    for i, (name, sec) in enumerate(sorted_items):
        w = (sec / total_seconds) * total_w if total_seconds > 0 else 0
        if w < 1:
            w = 1
        color = colors.HexColor(palette[i % len(palette)])
        drawing.add(Rect(x, len(sorted_items) * 18 + 2, w, bar_h,
                         fillColor=color, strokeColor=None))
        x += w

    # 凡例
    for i, (name, sec) in enumerate(sorted_items):
        y = (len(sorted_items) - 1 - i) * 18
        color = colors.HexColor(palette[i % len(palette)])
        drawing.add(Rect(x_offset, y + 2, 10, 10, fillColor=color, strokeColor=None,
                         rx=2, ry=2))
        pct = (sec / total_seconds * 100) if total_seconds > 0 else 0
        drawing.add(String(
            x_offset + 14, y + 3,
            f"{name}  {_fmt_duration(sec)} ({pct:.0f}%)",
            fontName="HeiseiKakuGo-W5", fontSize=9,
            fillColor=colors.HexColor("#333333"),
        ))

    return [drawing, Spacer(1, 8)]


def _build_hourly_chart(hourly_data: list[dict]):
    """時間帯別のアクティビティバーチャートを生成する"""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.graphics.shapes import Drawing, Rect, String, Line

    hour_totals: dict[str, float] = {}
    for r in hourly_data:
        h = r.get("hour", "00")
        sec = r.get("total_seconds", 0)
        hour_totals[h] = hour_totals.get(h, 0) + sec

    # 有効な時間帯のみ
    hours = [f"{i:02d}" for i in range(24)]
    max_sec = max(hour_totals.values()) if hour_totals else 1
    max_sec = max(max_sec, 1)

    drawing = Drawing(170 * mm, 80)
    bar_area_w = 155 * mm
    bar_h = 60
    x_start = 12 * mm
    y_base = 10

    # 軸ライン
    drawing.add(Line(x_start, y_base, x_start + bar_area_w, y_base,
                     strokeColor=colors.HexColor("#cccccc"), strokeWidth=0.5))

    bar_w = bar_area_w / 24 - 1
    for i, h in enumerate(hours):
        sec = hour_totals.get(h, 0)
        if sec > 0:
            bh = (sec / max_sec) * bar_h
            x = x_start + i * (bar_w + 1)
            # バーの色: 時間帯による
            if 6 <= i < 12:
                c = "#4a90d9"  # 午前: 青
            elif 12 <= i < 18:
                c = "#3fb950"  # 午後: 緑
            elif 18 <= i < 22:
                c = "#f0883e"  # 夕方: オレンジ
            else:
                c = "#bc8cff"  # 深夜・早朝: 紫
            drawing.add(Rect(x, y_base, bar_w, bh, fillColor=colors.HexColor(c),
                             strokeColor=None, rx=1, ry=1))

        # ラベル（3時間ごと）
        if i % 3 == 0:
            drawing.add(String(
                x_start + i * (bar_w + 1), y_base - 10,
                f"{h}", fontName="HeiseiKakuGo-W5", fontSize=7,
                fillColor=colors.HexColor("#888888"),
            ))

    return drawing


def _build_daily_trend_chart(days: list[dict]):
    """月の日別推移チャートを生成する"""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.graphics.shapes import Drawing, Rect, String, Line

    n = len(days)
    if n == 0:
        return Drawing(170 * mm, 20)

    max_sec = max((d["total_seconds"] for d in days), default=1) or 1

    chart_w = 165 * mm
    chart_h = 70
    drawing = Drawing(170 * mm, chart_h + 25)
    x_start = 5 * mm
    y_base = 15

    # 軸ライン
    drawing.add(Line(x_start, y_base, x_start + chart_w, y_base,
                     strokeColor=colors.HexColor("#cccccc"), strokeWidth=0.5))

    bar_w = chart_w / n - 1
    for i, d_info in enumerate(days):
        sec = d_info["total_seconds"]
        x = x_start + i * (bar_w + 1)

        if sec > 0:
            bh = (sec / max_sec) * chart_h
            d_dt = date.fromisoformat(d_info["date"])
            # 週末は色を変える
            if d_dt.weekday() >= 5:
                c = "#f0883e"
            else:
                c = "#4a90d9"
            drawing.add(Rect(x, y_base, bar_w, bh, fillColor=colors.HexColor(c),
                             strokeColor=None, rx=1, ry=1))

        # 日付ラベル（5日ごと or 1日目）
        day_num = int(d_info["date"][-2:])
        if day_num == 1 or day_num % 5 == 0:
            drawing.add(String(
                x, y_base - 10,
                str(day_num), fontName="HeiseiKakuGo-W5", fontSize=7,
                fillColor=colors.HexColor("#888888"),
            ))

    return drawing
